
# SPDX-License-Identifier: Apache-2.0
version: '2.1'

volumes:
  nft_pgdata:
  nft_walletstore:

networks:
  test:
    name: ${COMPOSE_NETWORK_NAME}

services:

  explorerdb.example.com:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.example.com
    hostname: explorerdb.example.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - nft_pgdata:/var/lib/postgresql/data
    networks:
      - test

  explorer.example.com:
    image: hyperledger/explorer:latest
    container_name: explorer.example.com
    hostname: explorer.example.com
    environment:
      - DATABASE_HOST=explorerdb.example.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=info
      - LOG_LEVEL_DB=info
      - LOG_LEVEL_CONSOLE=debug
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ${EXPLORER_CONFIG_FILE_PATH}:/opt/explorer/app/platform/fabric/config.json
      - ${EXPLORER_PROFILE_DIR_PATH}:/opt/explorer/app/platform/fabric/connection-profile
      - ${FABRIC_CRYPTO_PATH}:/tmp/crypto
      - nft_walletstore:/opt/explorer/wallet
    ports:
      - 9090:8080
    depends_on:
      explorerdb.example.com:
        condition: service_healthy
    networks:
      - test